-- 初期マイグレーション(P0-2)。
-- 作品マスター・ユーザー・レビュー・保管庫の各テーブルと、関連する Enum 型を作成する。

-- Enum作成
CREATE TYPE "WorkType" AS ENUM ('ANIME', 'MANGA');

-- Enum作成
CREATE TYPE "WorkCountry" AS ENUM ('JP', 'KR', 'CN', 'TW', 'OTHER');

-- Enum作成
CREATE TYPE "Season" AS ENUM ('WINTER', 'SPRING', 'SUMMER', 'FALL');

-- Enum作成
CREATE TYPE "WorkRelationType" AS ENUM ('ADAPTATION', 'PREQUEL', 'SEQUEL', 'PARENT', 'SIDE_STORY', 'CHARACTER', 'SUMMARY', 'ALTERNATIVE', 'SPIN_OFF', 'OTHER', 'SOURCE', 'COMPILATION', 'CONTAINS');

-- Enum作成
CREATE TYPE "PreferredLanguage" AS ENUM ('JA', 'KO');

-- Enum作成
CREATE TYPE "LibraryStatus" AS ENUM ('PLANNING', 'WATCHING', 'COMPLETED', 'ON_HOLD', 'DROPPED');

-- テーブル作成: 作品マスター
CREATE TABLE "works" (
    "id" INTEGER NOT NULL GENERATED BY DEFAULT AS IDENTITY,
    "anilist_id" INTEGER NOT NULL,
    "type" "WorkType" NOT NULL,
    "title_romaji" TEXT,
    "title_english" TEXT,
    "title_native" TEXT,
    "title_korean" TEXT,
    "genres" TEXT[],
    "country_of_origin" "WorkCountry" NOT NULL,
    "season" "Season",
    "season_year" INTEGER,
    "episodes" INTEGER,
    "chapters" INTEGER,
    "volumes" INTEGER,
    "cover_image_url" TEXT,
    "popularity" INTEGER,
    "average_score" INTEGER,
    "trending" INTEGER,
    "created_at" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,
    "updated_at" TIMESTAMP(3) NOT NULL,

    CONSTRAINT "works_pkey" PRIMARY KEY ("id")
);

-- テーブル作成: 作品タグ(AniList タグ + 連関度)
CREATE TABLE "work_tags" (
    "id" INTEGER NOT NULL GENERATED BY DEFAULT AS IDENTITY,
    "work_id" INTEGER NOT NULL,
    "name" TEXT NOT NULL,
    "rank" INTEGER NOT NULL,
    "created_at" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,

    CONSTRAINT "work_tags_pkey" PRIMARY KEY ("id")
);

-- テーブル作成: 原作-アニメ-続編-外伝 接続関係
CREATE TABLE "work_relations" (
    "id" INTEGER NOT NULL GENERATED BY DEFAULT AS IDENTITY,
    "source_work_id" INTEGER NOT NULL,
    "target_anilist_id" INTEGER NOT NULL,
    "target_work_id" INTEGER,
    "relation_type" "WorkRelationType" NOT NULL,
    "created_at" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,

    CONSTRAINT "work_relations_pkey" PRIMARY KEY ("id")
);

-- テーブル作成: ユーザー(メール+パスワード自前認証)
CREATE TABLE "users" (
    "id" INTEGER NOT NULL GENERATED BY DEFAULT AS IDENTITY,
    "email" TEXT NOT NULL,
    "password_hash" TEXT NOT NULL,
    "nickname" TEXT NOT NULL,
    "preferred_language" "PreferredLanguage" NOT NULL DEFAULT 'JA',
    "taste_keywords" TEXT[],
    "country" TEXT,
    "created_at" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,
    "updated_at" TIMESTAMP(3) NOT NULL,

    CONSTRAINT "users_pkey" PRIMARY KEY ("id")
);

-- テーブル作成: レビュー/評価
CREATE TABLE "reviews" (
    "id" INTEGER NOT NULL GENERATED BY DEFAULT AS IDENTITY,
    "work_id" INTEGER NOT NULL,
    "user_id" INTEGER NOT NULL,
    "rating" INTEGER NOT NULL,
    "body" TEXT NOT NULL,
    "is_spoiler" BOOLEAN NOT NULL DEFAULT false,
    "created_at" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,
    "updated_at" TIMESTAMP(3) NOT NULL,

    CONSTRAINT "reviews_pkey" PRIMARY KEY ("id")
);

-- テーブル作成: 保管庫(お気に入り/視聴状態)
CREATE TABLE "library_entries" (
    "id" INTEGER NOT NULL GENERATED BY DEFAULT AS IDENTITY,
    "user_id" INTEGER NOT NULL,
    "work_id" INTEGER NOT NULL,
    "status" "LibraryStatus" NOT NULL,
    "created_at" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,
    "updated_at" TIMESTAMP(3) NOT NULL,

    CONSTRAINT "library_entries_pkey" PRIMARY KEY ("id")
);

-- インデックス作成
CREATE UNIQUE INDEX "works_anilist_id_key" ON "works"("anilist_id");

-- インデックス作成
CREATE INDEX "works_type_idx" ON "works"("type");

-- インデックス作成
CREATE INDEX "works_country_of_origin_idx" ON "works"("country_of_origin");

-- インデックス作成
CREATE INDEX "works_season_season_year_idx" ON "works"("season", "season_year");

-- インデックス作成
CREATE UNIQUE INDEX "work_tags_work_id_name_key" ON "work_tags"("work_id", "name");

-- インデックス作成
CREATE INDEX "work_tags_name_idx" ON "work_tags"("name");

-- インデックス作成
CREATE UNIQUE INDEX "work_relations_source_work_id_target_anilist_id_relation_ty_key" ON "work_relations"("source_work_id", "target_anilist_id", "relation_type");

-- インデックス作成
CREATE INDEX "work_relations_target_anilist_id_idx" ON "work_relations"("target_anilist_id");

-- インデックス作成
CREATE UNIQUE INDEX "users_email_key" ON "users"("email");

-- インデックス作成
CREATE UNIQUE INDEX "reviews_work_id_user_id_key" ON "reviews"("work_id", "user_id");

-- インデックス作成
CREATE INDEX "reviews_work_id_idx" ON "reviews"("work_id");

-- インデックス作成
CREATE UNIQUE INDEX "library_entries_user_id_work_id_key" ON "library_entries"("user_id", "work_id");

-- インデックス作成
CREATE INDEX "library_entries_user_id_status_idx" ON "library_entries"("user_id", "status");

-- 外部キー追加: work_tags -> works
ALTER TABLE "work_tags" ADD CONSTRAINT "work_tags_work_id_fkey" FOREIGN KEY ("work_id") REFERENCES "works"("id") ON DELETE CASCADE ON UPDATE CASCADE;

-- 外部キー追加: work_relations -> works(接続元)
ALTER TABLE "work_relations" ADD CONSTRAINT "work_relations_source_work_id_fkey" FOREIGN KEY ("source_work_id") REFERENCES "works"("id") ON DELETE CASCADE ON UPDATE CASCADE;

-- 外部キー追加: work_relations -> works(接続先、未同期の間は NULL)
ALTER TABLE "work_relations" ADD CONSTRAINT "work_relations_target_work_id_fkey" FOREIGN KEY ("target_work_id") REFERENCES "works"("id") ON DELETE SET NULL ON UPDATE CASCADE;

-- 外部キー追加: reviews -> works
ALTER TABLE "reviews" ADD CONSTRAINT "reviews_work_id_fkey" FOREIGN KEY ("work_id") REFERENCES "works"("id") ON DELETE CASCADE ON UPDATE CASCADE;

-- 外部キー追加: reviews -> users
ALTER TABLE "reviews" ADD CONSTRAINT "reviews_user_id_fkey" FOREIGN KEY ("user_id") REFERENCES "users"("id") ON DELETE CASCADE ON UPDATE CASCADE;

-- 外部キー追加: library_entries -> users
ALTER TABLE "library_entries" ADD CONSTRAINT "library_entries_user_id_fkey" FOREIGN KEY ("user_id") REFERENCES "users"("id") ON DELETE CASCADE ON UPDATE CASCADE;

-- 外部キー追加: library_entries -> works
ALTER TABLE "library_entries" ADD CONSTRAINT "library_entries_work_id_fkey" FOREIGN KEY ("work_id") REFERENCES "works"("id") ON DELETE CASCADE ON UPDATE CASCADE;
